name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: GodotActionTest
  
jobs:
  export-windows-barichello:
    name: Windows Export (Barichello)
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI Setup
        run: |
          apt-get update
          apt-get install curl -y
          apt-get install build-essential -y
          apt-get install mingw-w64 -y
      - name: Rust Setup
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Toolchain Setup
        run: |
          rustup target add x86_64-pc-windows-gnu
      - name: Godot Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          cd ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls -l
      - name: Verify Build tools
        run: |
          rustup default
          rustup target list
          rustup --version
          rustc --version
          cargo --version
          whereis godot
          godot --headless --version
      - name: Windows Build
        run: |
          cd rust
          ls -la
          export GODOT4_BIN=godot
          cargo build --release --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/rust.dll target/release/rust.dll
          cd ..
          mkdir -v -p build/windows
          cd godot_action_test
          ls -la
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_barichello
          path: build/windows
  export-windows-chickensoft:
    name: Windows Export (Chickensoft)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: 4.2.1
          use-dotnet: false
      - name: Check Dependencies
        shell: cmd
        run: |
          rustup default
          rustc --version
          dir C:\Users\runneradmin\bin\
          echo %GODOT%
          echo %GODOT4%
          where godot
          godot --version
          godot --headless --version
      - name: Rust build
        working-directory: ${{github.workspace}}/rust
        run: |
          set GODOT4_BIN=godot
          cargo build --release
      - name: Godot export
        working-directory: ${{github.workspace}}/godot_action_test
        shell: cmd
        run: |
          mkdir ../build/windows
          %GODOT% --headless --verbose --export-release "Windows Desktop" ../build/windows/GodotActionTest.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_chickensoft
          path: build/windows
