name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: GodotActionTest
  
jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI Setup
        run: |
          apt-get update
          apt-get install curl -y
      - name: Rust Setup
        uses: dtolnay/rust-toolchain@stable
      - name: Godot Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          cd ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls -l
      # - name: Find Rust
      #   run: |
      #     apt-get update
      #     apt-get install rustc -y
      #     rustc --version
      #     rustup --version
      #     rustup update
      #     whereis cargo
      #     cargo --version
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd godot_action_test
          ls -la
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows
