name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: GodotActionTest
  
jobs:
  export-windows-rust-barichello:
    name: Windows Export Rust (Barichello)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify Rust
        run: |
          rustup default
          rustc --version
          cargo --version
      - name: Rust build
        working-directory: ${{github.workspace}}/rust
        run: |
          cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_rust_barichello
          path: rust/target/release/rust.dll

  export-windows-barichello:
    name: Windows Export (Barichello)
    runs-on: ubuntu-20.04
    needs: export-windows-rust-barichello
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Godot Export Template Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Download Rust artifact
        uses: actions/download-artifact@v3
        with:
          name: windows_rust_barichello
          path: rust/target/release/
      - name: Verify Build tools
        run: |
          ls -l ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls -l rust/target/release
          whereis godot
          godot --headless --version
      - name: Windows Build
        working-directory: ${{github.workspace}}/godot_action_test
        run: |
          mkdir -v -p ../build/windows
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_barichello
          path: build/windows

  export-windows-chickensoft:
    name: Windows Export (Chickensoft)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: chickensoft-games/setup-godot@v1.5.5
        name: Setup Godot
        with:
          version: 4.2.1
          use-dotnet: false
          path: ${{github.workspace}}/godot/install
          downloads-path: ${{github.workspace}}/godot/download
          bin-path: ${{github.workspace}}/godot/bin
      - name: Check Dependencies
        shell: cmd
        run: |
          rustup default
          rustc --version
          echo %GODOT%
          echo %GODOT4%
          where godot
      - name: Rust and Godot export
        working-directory: ${{github.workspace}}/godot_action_test
        shell: cmd
        run: |
          set GODOT4_BIN=godot
          mkdir ../build/windows
          export_win.bat
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_chickensoft
          path: build/windows
